name: main.yml

on: 
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to server
    runs-on: self-hosted
    env: 
      PROJECT_ROOT_DIR: /var/www/levt
      RELEASES_DIR: /var/www/levt/releases
      NEW_RELEASE_DIR: /var/www/levt/releases/$GITHUB_SHA
      STORAGE_DIR: /var/www/levt/storage
      ENV_FILE: /var/www/levt/.env
      CURRENT_DIR: /var/www/levt/current
      BUILD_DIR: $GITHUB_WORKSPACE
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p $RELEASES_DIR
      - run: mkdir -p $NEW_RELEASE_DIR && cp -r $GITHUB_WORKSPACE/* $NEW_RELEASE_DIR/
      - run: cd $NEW_RELEASE_DIR
      - run: rm -rf ./storage
      - run: ln -nfs $STORAGE_DIR $NEW_RELEASE_DIR/storage
      - run: ln -nfs $ENV_FILE $NEW_RELEASE_DIR/.env
      - run: ln -nfs $NEW_RELEASE_DIR $CURRENT_DIR
      - run: cd $CURRENT_DIR
      - run: composer install --prefer-dist --no-scripts -q -o
      - run: php artisan migrate
      - run: php artisan storage:link