name: main.yml

on: 
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to server
    runs-on: self-hosted
    env: 
      PROJECT_ROOT_DIR: /var/www/levt
      RELEASES_DIR: /var/www/levt/releases
      NEW_RELEASE_DIR: /var/www/levt/releases/$GITHUB_SHA
      STORAGE_DIR: /var/www/levt/storage
      ENV_FILE: /var/www/levt/.env
      CURRENT_DIR: /var/www/levt/current
      BUILD_DIR: $GITHUB_WORKSPACE
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p $RELEASES_DIR
      - run: mkdir -p /var/www/levt/releases/$GITHUB_SHA && cp -r $GITHUB_WORKSPACE/* /var/www/levt/releases/$GITHUB_SHA/
      - run: cd /var/www/levt/releases/$GITHUB_SHA
      - run: rm -rf ./storage
      - run: ln -nfs $STORAGE_DIR /var/www/levt/releases/$GITHUB_SHA/storage
      - run: ln -nfs $ENV_FILE /var/www/levt/releases/$GITHUB_SHA/.env
      - run: ln -nfs /var/www/levt/releases/$GITHUB_SHA $CURRENT_DIR
      - run: cd $CURRENT_DIR/backend/levt
      - run: composer install --prefer-dist --no-scripts -q -o
      - run: php artisan migrate
      - run: php artisan storage:link